### ISSUE TITLE
Model appear as though there is no lighting

### ISSUE THREAD

**Issue by Antsushi** [joeroe/piwigo-3dhop#1]
Hi,

I have recently installed your plugin on my Piwigo gallery because I thought it would be perfect for what I want to do, but unfortunately I am having issues with getting my .ply models to display correctly. They load and I can manipulate them, however they appear flat and not detailed - almost as through there's no light source. The lighting functions (disable/enable and enable light control) don't seem to do anything.

This is what my models look like:

![3Dhop](https://user-images.githubusercontent.com/57841891/72991406-dba63a80-3de9-11ea-8b7b-ae700b58dd3b.png)

![3DHop_2](https://user-images.githubusercontent.com/57841891/72991414-e06aee80-3de9-11ea-8916-0edb4a9dd6a5.png)

Could you please let me know what I can do to fix the issue?

**Comment by Antsushi** [comment]
I just wanted to let you (and any other potential users) that I have solved the issue. The problem was not with 3Dhop or the plugin, but with my models. In order to make them work I had to import them to MeshLab, and export them as .ply, ticking the Binary Eencoding and Vert -> Normal boxes. That seemed to solve the issue!

**Comment by gapantos** [comment]
Hi Antsushi, sorry for the delayed response and glad you got it working.

I think Normals are needed for lighting a "single-resolution" mesh in 3D hop. Had to look it up though. http://vcg.isti.cnr.it/3dhop/documentation/3DHOP_Models_Preparation.pdf.
I think pointclouds and streaming meshes can use the global light, but if you find any issues with this let us know incase we've forgotten to turn something on.
If you have any models without normals (I sometimes end up with this when dealing with some laserscan formats) you can use meshlab or cloud compare to generate them.

Didn't know the binary encoding could be an issue so thanks for the heads up, I've been having compatibility with ply binary-or-not files across some other packages too.

Hope you manage to do what you need to with it.
